import javax.servlet.http.*;
import javax.servlet.*;
import java.io.*;
import java.sql.*;

public class Edit extends HttpServlet {
public Edit(){}
protected void doPost(HttpServletRequest request , HttpServletResponse response) throws ServletException, IOException{
response.setContentType("text/html");
PrintWriter out = response.getWriter();
String rollno= request.getParameter("rollno");
String user= request.getParameter("user");
String pass= request.getParameter("pass");

try{
 Class.forName("com.mysql.jdbc.Driver");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/oshp",user,pass);
  PreparedStatement ps=con.prepareStatement("select * from student where rollno=?;");
  ps.setString(1,rollno);
  ResultSet rs = ps.executeQuery();
  rs.next();

 out.println("<html><title>Edit Student Details</title>");
  out.println("<link rel= 'icon' href= '/bcsctc/Images/logo.png' type= 'image/x-icon'>");
  out.println("<body style='background-color:#f5f5f5'>");
  out.println("<center>");
  out.println("<img alt='KUCET' src='/bcsctc/Images/image-preview.jpg' style='height:max-width:100%;height:auto;' />");
  out.println("<h2><u>Student Details</u></h2><br>");
  out.println("<form method='post'>");
  out.println("<table style='float:center;'>");
  out.println("<tr>");
  out.println("<td><strong>No. : </strong></td>");
  out.println("<td><input value='"+rs.getString(2)+"' type='text' maxlength='5' name='no'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Date of Joining : </strong></td>");
  out.println("<td><input value='"+rs.getString(3)+"' type='text' maxlength='10' placeholder= 'DD-MM-YYYY' name='admdate'/></td>");
  out.println("<td><strong>Fee Reimbursement : </strong></td>");
  out.println("<td><input value='"+rs.getString(34)+"' maxlength='4' type='text' oninput='this.value = this.value.toUpperCase()' name='feereim'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Roll Number : </strong></td>");
  out.println("<td><input value='"+rs.getString(1)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='10' name='rollno'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Course : </strong></td>");
  out.println("<td><input value='"+rs.getString(4)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='6' name='course'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Branch : </strong></td>");
  out.println("<td><input value='"+rs.getString(5)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='50' name='branch'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Year of Study : </strong></td>");
  out.println("<td><input value='"+rs.getString(6)+"' type='text' maxlength='9' placeholder='YYYY-YYYY' name='yos'/></td>");
 out.println(" </tr>");
  out.println("<tr>");
  out.println("<td><strong>Name : </strong></td>");
  out.println("<td><input value='"+rs.getString(7)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='50' name='name'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Father Name: </strong></td>");
  out.println("<td><input value='"+rs.getString(8)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='50' name='fname'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Mother Name: </strong></td>");
  out.println("<td><input value='"+rs.getString(9)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='50' name='mname'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Date of Birth : </strong></td>");
  out.println("<td><input value='"+rs.getString(10)+"' type='text' maxlength='10' placeholder='DD-MM-YYYY' name='dob'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Place of birth: </strong></td>");
  out.println("<td><input value='"+rs.getString(11)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='30' name='pob'/></td>");
  out.println("<td><strong>&nbsp;&nbsp;Aadhar No : </strong></td>");
  out.println("<td><input value='"+rs.getString(12)+"' type='text' maxlength='16' name='aadharno'/></td>");
  out.println("<td><strong>Gender : </strong></td>");
  out.println("<td><input value='"+rs.getString(35)+"' type='text' maxlength='6' oninput='this.value = this.value.toUpperCase()' name='gen'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Caste : </strong></td>");
  out.println("<td><input value='"+rs.getString(13)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='4' name='caste'/></td>");
  out.println("<td><strong> &nbsp;&nbsp;SubCaste : </strong></td>");
  out.println("<td><input value='"+rs.getString(14)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='30' name='subcaste'/></td>");
  out.println("<td><strong>&nbsp; Annual Income: </strong></td>");
  out.println("<td><input value='"+rs.getString(15)+"' type='text' maxlength='12' name='income'/></td>");
  out.println("<td><strong>Rank : </strong></td>");
  out.println("<td><input value='"+rs.getString(16)+"' type='text' maxlength='7' name='rnk'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Caste Sl.No. : </strong></td>");
  out.println("<td><input value='"+rs.getString(17)+"' type='text' maxlength='5' name='casteno'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Address : </strong></td>");
  out.println("<td><textarea rows='5' maxlength='300' name='address'>"+rs.getString(18)+"</textarea></td>");
  out.println("<td><strong>Student Mobile No. : </strong></td>");
 out.println(" <td><input value='"+rs.getString(19)+"' type='text' maxlength='10' name='phone1'/></td>");
  out.println("<td><strong> Guardian Mobile No. : </strong></td>");
  out.println("<td><input value='"+rs.getString(20)+"' type='text' maxlength='13' name='phone2'/></td>");
  out.println("<td><strong>Email : </strong></td>");
  out.println("<td><input value='"+rs.getString(21)+"' type='text' maxlength='50' name='email'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Identification Marks : </strong></td>");
  out.println("<td><input value='"+rs.getString(22)+"' oninput='this.value = this.value.toUpperCase()' type='text' maxlength='150' name='idmarks'/></td>");
  out.println("</tr>");
  out.println(" </table>");
  out.println("<br><br>");
  out.println(" <table>");
  out.println("<tr>");
  out.println("<td><strong>Particulars of the qualifying exam : </strong></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Qualifying Exam : </strong></td>");
  out.println("<td><input value='"+rs.getString(23)+"' type='text' maxlength='30' name='qexam'/></td>");
  out.println("<td></td>");
	out.println("<td><strong>Certificates Submitted : </strong></td>");
	out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Regd. No. : </strong></td>");
  out.println("<td><input value='"+rs.getString(24)+"' type='text' maxlength='15' name='regdno'/></td>");
  out.println("<td></td>");
	out.println("<td><strong>10th Standard </strong></td>");
  out.println("<td><input value='"+rs.getString(36)+"' type='text' maxlength='4' name='ssc'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Month & Year of Pass : </strong></td>");
  out.println("<td><input value='"+rs.getString(25)+"' type='text' maxlength='7' name='myop'/></td>");
  out.println("<td></td>");
  out.println("<td><strong>Previous year's Originals </strong></td>");
  out.println("<td><input value='"+rs.getString(37)+"' type='text' maxlength='4' name='inter'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>Marks Secured(%) : </strong></td>");
  out.println("<td><input value='"+rs.getString(26)+"' type='text' maxlength='6' name='marks'/></td>");
  out.println("<td></td>");
  out.println("<td><strong>Previous year's TC </strong></td>");
  out.println("<td><input value='"+rs.getString(38)+"' type='text' maxlength='4' name='itc'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>College Name : </strong></td>");
  out.println("<td><input value='"+rs.getString(27)+"' type='text' maxlength='50' name='college'/></td>");
  out.println("<td></td>");
  out.println("<td><strong>Photos </strong></td>");
  out.println("<td><input value='"+rs.getString(39)+"' type='text' maxlength='4' name='photos'/></td>");
  out.println("</tr>");
  out.println("<tr>");
  out.println("<td><strong>TC No./Date : </strong></td>");
  out.println("<td><input value='"+rs.getString(28)+"' type='text' maxlength='20' name='itcdate'/></td>");
  out.println("</tr>");
  out.println("</table>");

out.println("<br><br>");
out.println("<table>");
out.println("<tr>");
out.println("<th>Transfer Certificate Issued on </th>");
out.println("<th>&nbsp;&nbsp;&nbsp;&nbsp;Bonafide Certificate Issued on </th>");
out.println("<th>&nbsp;&nbsp;&nbsp;&nbsp;Conduct Certificate Issued on </th>");
out.println("<th>&nbsp;&nbsp;&nbsp;&nbsp;Migration Certificate Issued on </th>");
out.println("</tr>");
out.println("<tr>");
out.println("<th><textarea rows='3' placeholder='DD-MM-YYYY' maxlength='100' name='tcdate'>"+rs.getString(30)+"</textarea></th>");
out.println("<th><textarea rows='3' placeholder='DD-MM-YYYY' maxlength='100' name='bcdate'>"+rs.getString(31)+"</textarea></th>");
out.println("<th><textarea rows='3' placeholder='DD-MM-YYYY' maxlength='100' name='scdate'>"+rs.getString(32)+"</textarea></th>");
out.println("<th><textarea rows='3' placeholder='DD-MM-YYYY' maxlength='100' name='mcdate'>"+rs.getString(33)+"</textarea></th>");
out.println("</tr>");
out.println("</table>");
out.println("<br><br>");

  out.println("<table>");
  out.println("<tr>");
  out.println("<td><strong>Remarks : </strong></td>");
  out.println("<td><textarea rows='2' maxlength='300' cols='60' name='remarks'>"+rs.getString(29)+"</textarea></td>");
  out.println("</tr>");
  out.println("</table>");
  out.println("<br><br>");
  out.println("<input type='submit' value='Update & Save' formaction='Update'/>");
  out.println("<input type='submit' value='Cancel' formaction='/bcsctc'/>");
  out.println("<input type='submit' value='---DELETE---' formaction='Delete'  />");
  out.println("</form>");
  out.println("<br><br>");
  out.println("<style>");
  out.println(".footer {");
   out.println(" position: ;");
   out.println(" font-size:8px;");
  out.println("  left: 0;");
 out.println("   bottom: 0;");
 out.println("   width: 100%;");
 out.println("   background-color:#ededed;");
 out.println("   color: black;");
 out.println("   text-align: center;");
 out.println(" }");
 out.println(" </style>");
 out.println(" <div class='footer'>");
 out.println("   <p>Copyright 2023 &copy; Developed by Team Kaboom</p>");
 out.println("</div>");
 out.println("</center></body></html>");
 con.close();
}catch(Exception e){
out.println("<center><h2>_Error_</h2><strong>Error</strong> :&nbsp;"+ e );
 out.println("<br><br><form><input type='button' value='Back' onclick='history.go(-1)'>");
 out.println("<input type='submit' value='Add Students' formaction='/bcsctc/addition.html'></form><br><br><br></center>");
}
}
}
