import javax.servlet.http.*;
import javax.servlet.*;
import java.io.*;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
//LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")
public class Search extends HttpServlet {
public Search(){}
protected void doPost(HttpServletRequest request , HttpServletResponse response) throws ServletException, IOException{
response.setContentType("text/html");
PrintWriter out = response.getWriter();
String rollno= request.getParameter("rollno");
try{
  Connection con = DBUtil.getConnection();
 //Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
 PreparedStatement ps=con.prepareStatement("select * from student where rollno=?;");
 ps.setString(1,rollno);
 ResultSet rs = ps.executeQuery();
 rs.next();
 //rs.first();

  out.println("<html><title>Student Details</title>");
   out.println("<link rel= 'icon' href= '/bcsctc/Images/logo.png' type= 'image/x-icon'>");
   out.println("<body style='background-color:#f5f5f5'>");
   out.println("<center>");
   out.println("<a href='/bcsctc'><img alt='LOGO' src='/bcsctc/Images/image-preview.jpg' style='max-width:100%;height:auto;' /></a>");
   out.println("<h2><u>Student Details</u></h2>");
   out.println("<form method='post'>");
   out.println("<p style='text-align:right'>");
   out.println("<input type='password' placeholder='Enter Username' name='user' size='11' />");
   out.println("<input type='password' placeholder='Enter Password' name='pass' size='11' />");
   out.println("<input type='submit' value='Edit Student Details' formaction='Edit'/>");
   out.println("</p><br>");
   out.println("<table style='float:center;'>");
   out.println("<tr>");
   out.println("<td><strong>No. : </strong></td>");
   out.println("<td>"+rs.getString(2)+"</td>");
   out.println("<td><strong>Date of Joining : </strong></td>");
   out.println("<td>"+rs.getString(3)+"</td>");
   out.println("<td><strong>Fee Reimbursement : </strong></td>");
   out.println("<td>"+rs.getString(34)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Roll Number : </strong></td>");
   out.println("<td><input type='text' name='rollno' size='10' value=" +rs.getString(1)+ "></td>");
   out.println("<td><strong>Course : </strong></td>");
   out.println("<td>"+rs.getString(4)+"</td>");
   out.println("<td><strong>Branch : </strong></td>");
   out.println("<td>"+rs.getString(5)+"</td>");
   out.println("<td><strong>Year of Study : </strong></td>");
   out.println("<td>"+rs.getString(6)+"</td>");
  out.println(" </tr>");
   out.println("<tr>");
   out.println("<td><strong>Name : </strong></td>");
   out.println("<td>"+rs.getString(7)+"</td>");
   out.println("<td><strong>Father Name: </strong></td>");
   out.println("<td>"+rs.getString(8)+"</td>");
   out.println("<td><strong>Mother Name: </strong></td>");
   out.println("<td>"+rs.getString(9)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Date of Birth : </strong></td>");
   out.println("<td>"+rs.getString(10)+"</td>");
   out.println("<td><strong>Place of birth: </strong></td>");
   out.println("<td>"+rs.getString(11)+"</td>");
   out.println("<td><strong>Aadhar No : </strong></td>");
   out.println("<td>"+rs.getString(12)+"</td>");
   out.println("<td><strong>Gender : </strong></td>");
	 out.println("<td>"+rs.getString(35)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Caste : </strong></td>");
   out.println("<td>"+rs.getString(13)+"</td>");
   out.println("<td><strong> SubCaste : </strong></td>");
   out.println("<td>"+rs.getString(14)+"</td>");
   out.println("<td><strong> Annual Income: </strong></td>");
   out.println("<td>"+rs.getString(15)+"</td>");
   out.println("<td><strong>Rank : </strong></td>");
   out.println("<td>"+rs.getString(16)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Caste Sl.No. : </strong></td>");
   out.println("<td>"+rs.getString(17)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Address : </strong></td>");
   out.println("<td>"+rs.getString(18)+"</td>");
   out.println("<td><strong>Phone No. : </strong></td>");
  out.println(" <td>"+rs.getString(19)+"</td>");
   out.println("<td><strong> Mobile No. : </strong></td>");
   out.println("<td>"+rs.getString(20)+"</td>");
   out.println("<td><strong>Email : </strong></td>");
   out.println("<td>"+rs.getString(21)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Identification Marks : </strong></td>");
   out.println("<td>"+rs.getString(22)+"</td>");
   out.println("</tr>");
  out.println(" </table>");
  out.println("<br><br>");
  out.println(" <table>");
  out.println("<tr>");
  out.println("<td><strong>Particulars of the qualifying exam : </strong></td>");
  out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Qualifying Exam : </strong></td>");
   out.println("<td>"+rs.getString(23)+"</td>");
   out.println("<td></td>");
   out.println("<td><strong>Certificates Submitted : </strong></td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Regd. No. : </strong></td>");
   out.println("<td>"+rs.getString(24)+"</td>");
   out.println("<td></td>");
   out.println("<td><strong>10th Standard </strong></td>");
   out.println("<td>"+rs.getString(36)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Month & Year of Pass : </strong></td>");
   out.println("<td>"+rs.getString(25)+"</td>");
   out.println("<td></td>");
   out.println("<td><strong>Previous year's Originals </strong></td>");
   out.println("<td>"+rs.getString(37)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>Marks Secured(%) : </strong></td>");
   out.println("<td>"+rs.getString(26)+"</td>");
   out.println("<td></td>");
   out.println("<td><strong>Previous year's TC </strong></td>");
   out.println("<td>"+rs.getString(38)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>College Name : </strong></td>");
   out.println("<td>"+rs.getString(27)+"</td>");
   out.println("<td></td>");
   out.println("<td><strong>Photos </strong></td>");
   out.println("<td>"+rs.getString(39)+"</td>");
   out.println("</tr>");
   out.println("<tr>");
   out.println("<td><strong>TC No./Date : </strong></td>");
   out.println("<td>"+rs.getString(28)+"</td>");
   out.println("</tr>");
   out.println("</table>");
out.println("<br><br>");
out.println("<table>");
out.println("<tr>");
out.println("<th>Transfer Certificate Issued on </th>");
out.println("<th>&nbsp;&nbsp;&nbsp;&nbsp;Bonafide Certificate Issued on </th>");
out.println("<th>&nbsp;&nbsp;&nbsp;&nbsp;Conduct Certificate Issued on </th>");
out.println("<th>&nbsp;&nbsp;&nbsp;&nbsp;Migration Certificate Issued on </th>");
out.println("</tr>");
out.println("<tr>");
out.println("<th>"+rs.getString(30)+"</th>");
out.println("<th>"+rs.getString(31)+"</th>");
out.println("<th>"+rs.getString(32)+"</th>");
out.println("<th>"+rs.getString(33)+"</th>");
out.println("</tr>");
out.println("</table>");
out.println("<br><br>");
   out.println("<table>");
   out.println("<tr>");
   out.println("<td><strong>Remarks : </strong></td>");
   out.println("<td>"+rs.getString(29)+"</td>");
   out.println("</tr>");
   out.println("</table>");
   out.println("<br><br>");
     out.println("<input type='submit' value='Get Transfer Certificate' formaction='TC' />");
     out.println("<input type='submit' value='Get Bonafide Certificate' formaction='BC' />");
     out.println("<input type='submit' value='Get Study & Conduct Certificate' formaction='SC' />");
     out.println("<input type='submit' value='Get Migration Certificate' formaction='MC' />");
// out.println("<input type='submit' value='Edit Details' formaction='Edit'/>");
   out.println("<br><br><input type='button' value='Back' onclick='history.go(-1)'>");
   out.println("<input type='button' value='Print Details' onclick='window.print()'>");
   out.println("</form>");
   out.println("<br>");
  out.println("<style>");
  out.println(".footer {");
   out.println(" position: ;");
   out.println(" font-size:8px;");
  out.println("  left: 0;");
 out.println("   bottom: 0;");
 out.println("   width: 100%;");
 out.println("   background-color:#ededed;");
 out.println("   color: black;");
 out.println("   text-align: center;");
 out.println(" }");
 out.println(" </style>");
 out.println(" <div class='footer'>");
 out.println("   <p>Copyright 2023 &copy; Developed by Team Kaboom</p>");
 out.println("</div>");
 out.println("</center></body></html>");
 con.close();
}catch(Exception e){
out.println("<center><h2>You are not in Database</h2><strong>Error</strong> :&nbsp;"+ e );
 out.println("<br><br><form><input type='button' value='Search Again' onclick='history.go(-1)'>");
 out.println("<input type='submit' value='Add Students' formaction='/bcsctc/addition.html'></form><br><br><br>");
}
}
}
